# Generated by Django 4.2.5 on 2023-09-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='https://i.blogs.es/173100/astra-rocket/1366_2000.jpeg', upload_to=''),
        ),
    ]
